@startuml
!pragma layout smetana
title Plataforma Web FST\nPaquete 1 - Autenticacion y gestion de usuarios
left to right direction
skinparam packageStyle rectangle
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor White
  BorderColor DarkSlateGray
}
actor "Usuario\nautenticado" as UA
actor "Investigador" as INV
actor "Administrador" as ADMIN
UA <|-- INV
UA <|-- ADMIN
rectangle "Plataforma Web FST - Paquete 1" {
  usecase "Iniciar sesion\ncorreo @ipn.mx + contrasena" as UC11
  usecase "Cerrar sesion\nInvalida token JWT" as UC12
  usecase "Verificar rol y permisos\nInvestigador vs. Administrador" as UC14
  usecase "Gestionar cuenta de usuario" as UC15
  usecase "Cambiar contrasena\nal primer acceso (obligatorio)" as UC15a
  usecase "Desactivar cuenta de usuario" as UC15b
  usecase "Actualizar perfil propio" as UC16
  usecase "Crear cuenta de usuario" as UC17
}
UA --> UC11
UA --> UC12
INV --> UC11
INV --> UC16
ADMIN --> UC15
ADMIN --> UC17
UC11 ..> UC14 : <<include>>
UC15 ..> UC15a : <<include>>
UC15 ..> UC15b : <<include>>
UC17 ..> UC15a : <<include>>
@enduml
